import '../models/app_models.dart';

final List<Building> initialSeedBuildings = [
  Building(
    id: 'b1',
    name: 'عمارة القدس',
    location: 'صنعاء - حدة',
    totalUnits: 15,
  ),
  Building(
    id: 'b2',
    name: 'عمارة النور',
    location: 'صنعاء - الجامعة',
    totalUnits: 10,
  ),
  Building(
    id: 'b3',
    name: 'عمارة الريان',
    location: 'صنعاء - بيت بوس',
    totalUnits: 8,
  ),
];

final List<Unit> initialSeedUnits = [
  Unit(
    id: 'u101',
    buildingId: 'b1',
    number: 'A101',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 500,
    currentTenant: 'عبدالله حسين',
  ),
  Unit(
    id: 'u102',
    buildingId: 'b1',
    number: 'A102',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 500,
    currentTenant: 'محمد أحمد',
  ),
  Unit(
    id: 'u103',
    buildingId: 'b1',
    number: 'A103',
    buildingName: 'عمارة القدس',
    status: 'فارغة',
    monthlyRent: 480,
  ),
  Unit(
    id: 'u104',
    buildingId: 'b1',
    number: 'A104',
    buildingName: 'عمارة القدس',
    status: 'مؤجرة',
    monthlyRent: 520,
  ),
  Unit(
    id: 'u105',
    buildingId: 'b1',
    number: 'A105',
    buildingName: 'عمارة القدس',
    status: 'قيد التجهيز',
    monthlyRent: 500,
  ),
  Unit(
    id: 'u106',
    buildingId: 'b1',
    number: 'A106',
    buildingName: 'عمارة القدس',
    status: 'صيانة',
    monthlyRent: 500,
  ),
  Unit(
    id: 'u201',
    buildingId: 'b2',
    number: 'B101',
    buildingName: 'عمارة النور',
    status: 'مؤجرة',
    monthlyRent: 450,
    currentTenant: 'أحمد علي',
  ),
  Unit(
    id: 'u202',
    buildingId: 'b2',
    number: 'B102',
    buildingName: 'عمارة النور',
    status: 'فارغة',
    monthlyRent: 450,
  ),
  Unit(
    id: 'u301',
    buildingId: 'b3',
    number: 'B103',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 450,
    currentTenant: 'يوسف محمد',
  ),
  Unit(
    id: 'u302',
    buildingId: 'b3',
    number: 'B104',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 450,
  ),
  Unit(
    id: 'u303',
    buildingId: 'b3',
    number: 'B105',
    buildingName: 'عمارة الريان',
    status: 'فارغة',
    monthlyRent: 400,
  ),
  Unit(
    id: 'u304',
    buildingId: 'b3',
    number: 'B106',
    buildingName: 'عمارة الريان',
    status: 'مؤجرة',
    monthlyRent: 420,
  ),
];

final List<Tenant> initialSeedTenants = [
  Tenant(
    id: 't1',
    name: 'محمد أحمد',
    phone: '777 888 999',
    nationalId: '109283746',
  ),
  Tenant(
    id: 't2',
    name: 'أحمد علي',
    phone: '711 222 333',
    nationalId: '109847261',
  ),
  Tenant(
    id: 't3',
    name: 'عبدالله حسين',
    phone: '733 444 555',
    nationalId: '102938475',
  ),
  Tenant(
    id: 't4',
    name: 'يوسف محمد',
    phone: '770 666 777',
    nationalId: '108374625',
  ),
];

final List<Contract> initialSeedContracts = [
  Contract(
    id: '105',
    tenantName: 'محمد أحمد',
    unitName: 'A102 - عمارة القدس',
    buildingName: 'عمارة القدس',
    monthlyRent: 500,
    currency: 'USD',
    startDate: '2024/01/01',
    endDate: '2025/12/31',
    status: 'نشط',
  ),
  Contract(
    id: '104',
    tenantName: 'أحمد علي',
    unitName: 'B101 - عمارة النور',
    buildingName: 'عمارة النور',
    monthlyRent: 450,
    currency: 'USD',
    startDate: '2024/02/01',
    endDate: '2025/12/31',
    status: 'نشط',
  ),
  Contract(
    id: '103',
    tenantName: 'عبدالله حسين',
    unitName: 'A101 - عمارة القدس',
    buildingName: 'عمارة القدس',
    monthlyRent: 500,
    currency: 'USD',
    startDate: '2023/01/01',
    endDate: '2023/12/31',
    status: 'منتهي',
  ),
  Contract(
    id: '102',
    tenantName: 'يوسف محمد',
    unitName: 'B103 - عمارة الريان',
    buildingName: 'عمارة الريان',
    monthlyRent: 450,
    currency: 'USD',
    startDate: '2024/01/01',
    endDate: '2025/12/31',
    status: 'نشط',
  ),
];

final List<Payment> initialSeedPayments = [
  Payment(
    id: 'p1',
    contractId: '105',
    tenantName: 'محمد أحمد',
    contractInfo: '#105 - A102',
    amount: 500,
    currency: '\$',
    paymentDate: '2024/05/01',
    status: 'مدفوع',
    method: 'نقداً (Cash)',
  ),
  Payment(
    id: 'p2',
    contractId: '104',
    tenantName: 'أحمد علي',
    contractInfo: '#104 - B101',
    amount: 250,
    currency: '\$',
    paymentDate: '2024/05/01',
    status: 'جزئي',
    method: 'تحويل بنكي',
  ),
  Payment(
    id: 'p3',
    contractId: '103',
    tenantName: 'عبدالله حسين',
    contractInfo: '#103 - A101',
    amount: 500,
    currency: '\$',
    paymentDate: '2024/04/30',
    status: 'متأخر',
    method: 'غير مدفوع بعد',
  ),
  Payment(
    id: 'p4',
    contractId: '102',
    tenantName: 'يوسف محمد',
    contractInfo: '#102 - B103',
    amount: 450,
    currency: '\$',
    paymentDate: '2024/05/01',
    status: 'مدفوع',
    method: 'نقداً (Cash)',
  ),
];

final List<MaintenanceExpense> initialSeedMaintenances = [
  MaintenanceExpense(
    id: 'm1',
    description: 'صيانة سباكة الحمام وتغيير صمامات',
    amount: 45,
    currency: '\$',
    unitName: 'A106 - عمارة القدس',
    date: '2024/05/02',
  ),
];

final List<CurrencyModel> initialSeedCurrencies = [
  CurrencyModel(
    code: 'USD',
    name: 'دولار أمريكي',
    symbol: '\$',
    isBase: true,
    rate: 1.0,
  ),
  CurrencyModel(
    code: 'SAR',
    name: 'ريال سعودي',
    symbol: '﷼',
    isBase: false,
    rate: 3.75,
  ),
  CurrencyModel(
    code: 'YER',
    name: 'ريال يمني',
    symbol: '﷼',
    isBase: false,
    rate: 530.0,
  ),
];
