// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZvKluD49tAKvq-ln4T1UWLsfDB7-Apac',
    appId: '1:299154081204:android:ef5716df6b585980cf5ee1',
    messagingSenderId: '299154081204',
    projectId: 'emtilak-app-2026',
    storageBucket: 'emtilak-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qhDBEN2TQAJfUNdnd9Vypqfba07Lu5g',
    appId: '1:299154081204:ios:8f06f1f8cedfdd9fcf5ee1',
    messagingSenderId: '299154081204',
    projectId: 'emtilak-app-2026',
    storageBucket: 'emtilak-app-2026.firebasestorage.app',
    androidClientId: '299154081204-cor7jccp4phebq28b5k4hm3chgf39umj.apps.googleusercontent.com',
    iosClientId: '299154081204-6gg9np1ouh33d6t711o4v3mvr01t98df.apps.googleusercontent.com',
    iosBundleId: 'com.example.emtilak',
  );
}
